name: diploy Dist
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4
       # echo "Cloning repo.."
       # echo "${{toJson(github)}}"
       # git clone https://github.com/${{github.repository}}.
       
    - name: Install Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: print node version
      run: node -v
    - name: install dependencies
      run: npm ci
    - name: Run test
      run: npm run test
